### ISSUE TITLE
tree_explorer fail to render in Pycharm

### ISSUE THREAD

**Issue by RaphaelRibes** [cjyetman/network.r2d3#33]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/>, <https://community.rstudio.com/> or email Mauro Lepore at <mauro@2degrees-investing.org>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

When starting the function tree_explorer on PyCharm Professional (2024.3) with the plugin `R Language for IntelliJ (243.21565.245)` I get this error:

```
> network.r2d3::tree_explorer(hc)

Listening on http://127.0.0.1:3819
Warning: Error in &&: 'length = 3' in coercion to 'logical(1)'
  14: runApp
  13: print.shiny.appobj
  12: base::print
  11: .jetbrains_runFunction [<text>#1]
  10: knit_print.default
   9: withCallingHandlers [<text>#1]
   8: <Anonymous> [<text>#1]
   7: doTryCatch
   6: tryCatchOne
   5: tryCatchList
   2: tryCatchList
   1: tryCatch
Error in is.call(funBody[[idx]]) && as.character(funBody[[idx]][[1]]) ==  : 
  'length = 3' in coercion to 'logical(1)'```

Here is the code I use
```r
hc <- hclust(dist(USArrests), "ave")
network.r2d3::tree_explorer(hc)
```
It works well in terminal tho, so i think it really is a problem coming from the plugin. I'm using the same interpreter as in my cmd R 4.4.2.

**Comment by cjyetman** [comment]
I don't know what PyCharm Professional is, so I don't think I can help with that directly. If you can come up with a reproducible example using R or RStudio I'll take a look at it.

**Comment by RaphaelRibes** [comment]
Yeah, I just tried some example that GPT gave me to test shiny and it's coming from there. Sorry for bothering you and thanks for your time !
